INTENTS = {
    "appointment.routing.reschedule": [
        "Reschedule",
        "Rescheduling",
        "Change",
        "Move",
        "Switch",
        "Postpone",
        "Postponing",
        "Modify",
        "Different day",
        "Different time",
        "I can't make it to my appointment",
        "I'm running late to my appointment",
        "I'm not going to be able to make my appointment",
        "I can't get to my appointment",
    ],
    "appointment.routing.cancel": [
        "cancel",
        "canceling",
        "cancelling",
        "cancellation",
        "call off my visit",
        "I don't need to come in anymore",
        "I'm not sick anymore",
        "I don't need that appointment now",
        "take me off the schedule",
    ],
    "appointment.routing.new_app": [
        "New ",
        "Book",
        "Set ",
        "Create",
        "Make an appointment",
        "Request an appointment",
        "Schedule an appointment",
        "Come in",
        "See the doctor",
        "See the nurse",
    ],
    "appointment.routing.existing": [
        "Confirm",
        "Check",
        "Verify",
        "Confirming",
        "Checking",
        "Verifying",
        "Get details",
        "Get information",
        "Figure out when",
        "Don't know when",
        "See when",
        "When am I",
        "What time",
        "What day",
    ],
    "appointment.routing.billing": [
        "billing",
        "bill",
        "payment",
        "pay",
    ],
    "appointment.routing.medication_refill": [
        "refill",
        "refilling",
        "medication",
        "meds",
        "prescription",
        "pharmacy",
    ],
}
