name: Deploy to QA

on:
  pull_request:
    types:
      - closed
    branches:
      - staging
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_DIAGFLOW }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Run main.py
        run: |
          python src/main.py
        env:
          AGENT_DISPLAY_NAME_ARCHIEVE: ${{ vars.AGENT_DISPLAY_NAME_ARCHIEVE }}
          AGENT_DISPLAY_NAME: ${{ vars.AGENT_DISPLAY_NAME }}
          GCS_BUCKET_URI_TO_RESTORE: ${{ vars.GCS_BUCKET_URI_TO_RESTORE }}
          LOCATION: ${{ vars.LOCATION }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          DIAGFLOW_URL: ${{ vars.DIAGFLOW_URL}}
          AUDIO_EXPORT_GCS_URL: ${{ vars.AUDIO_EXPORT_GCS_URL }}
          UPSERT_DATA_INTO_SPANNER_URL: ${{ vars.UPSERT_DATA_INTO_SPANNER_URL }}
  push_git:
    runs-on: ubuntu-latest
    needs: deploy
    environment: qa
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_DIAGFLOW }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: "Start the async job"
        run: |
          ACCESS_TOKEN=$(gcloud auth application-default print-access-token)

          curl -X POST ${{ vars.PROJECT_URL}}:export \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -d '{
            "dataFormat": "JSON_PACKAGE",
            "gitDestination": {
              "trackingBranch": "qa",
              "commitMessage": "Automated Commit"
            },
            "includeBigqueryExportSettings": true
          }'
